### PR TITLE
$ListFind("CLS","MAC","XML") had "XML" removed from it which lead to …

### PR DESCRIPTION
**Pull request by isc-jlechtne**
$ListFind("CLS","MAC","XML") had "XML" removed from it which lead to LOC files failing to import

### CODE REVIEW

**Review by isc-tleavitt — CHANGES_REQUESTED** [review]
Sure enough, this is causing CI failures. @isc-shuliu can you help get @isc-jlechtne up to speed on the debugging process for these?

**Comment by isc-tleavitt** [comment]
Should add a test for LOC files too while we're at it

**Comment by isc-shuliu** [comment]
The CI failures are caused by GitHub no longer having a 0.7.2 release artifact (not sure why) but changing the CI to download 0.7.3 release will fix it. I had a similar issue not long ago

**Comment by isc-shuliu** [comment]
After debugging with @isc-jlechtne today, we found that the latest change somehow caused resource "Covid19-bubble_chart_atelier.dashboard.dfi" fail to load

```
SAX XML Parser Error: Line: 3 Offset: 921 no declaration found for element 'dashboard' while processing /home/irisowner/zpm/tests/integration_tests/Test/PM/Integration/_data/resource-test/dfi/Covid19/bubble_chart_atelier.dashboard.xml at line 3 offset 921
...
```

**Comment by isc-shuliu** [comment]
@isc-tleavitt Any idea what went wrong with the `.dfi` resources?

**Comment by isc-jlechtne** [comment]
> After debugging with @isc-jlechtne today, we found that the latest change somehow caused resource "Covid19-bubble_chart_atelier.dashboard.dfi" fail to load in `tests/integration_tests/Test/PM/Integration/_data/resource-test`
> 
> ```
> SAX XML Parser Error: Line: 3 Offset: 921 no declaration found for element 'dashboard' while processing /home/irisowner/zpm/tests/integration_tests/Test/PM/Integration/_data/resource-test/dfi/Covid19/bubble_chart_atelier.dashboard.xml at line 3 offset 921
> ...
> ```

Covid19-Countries_bubble_atelier.pivot.dfi and TestLookupTable_short_atelier.lut as well

**Comment by isc-jlechtne** [comment]
@isc-shuliu @isc-tleavitt There seemed to be an issue using "text()" as a way to discern a wrapped xml file for .LOC files. Found an alternative solution by switching to node() instead an no longer needing to add back in "XML" from the original change.

**Comment by isc-shuliu** [comment]
I'm not familiar with this part of the codebase. But with unit tests passing we know we didn't break anything. 

Do we need a new unit test to ensure LOC files are properly imported with this change?

**Comment by isc-jlechtne** [comment]
Ah yes, a new unit test for LOC files should be added along with this change

**Review by isc-eneil — APPROVED** [review]

**Review by isc-tleavitt — APPROVED** [review]

**Comment by isc-tleavitt** [comment]
@isc-jlechtne great find! And @isc-eneil thank you for adding the unit test. Approved assuming CI passses.

**Review by isc-kiyer — APPROVED** [review]

**Comment by isc-eneil** [comment]
Oh @isc-tleavitt, that was actually @isc-jlechtne!

**Comment by isc-tleavitt** [comment]
I want to get this into v1 before v0.9.0 release, but would be good to sort out the CI first.

**Review by isc-kiyer — APPROVED** [review]

**Comment by isc-tleavitt** [comment]
CI is set, merging.

**Pull request merged**
