### PR TITLE
fix for 2023.1

### LINKED ISSUE #368: IPM fails to be installed on 2023.1
Due to significant changes in compiled code in IRIS 2023.1, IPM fails to be installed with the error `Could not find %ZLANGC00 routine contents`, which happens in 
https://github.com/intersystems/ipm/blob/master/src/%25ZPM/PackageManager.cls#L2279-L2280

2023.1 does not add `z` to Method Names in INT code anymore, and this code fails due to this

### PR DESCRIPTION
**Pull request by daimor**
fixes #368

### CODE REVIEW

**Comment by daimor** [comment]
@isc-rsingh, requires #370 for the CI fixes, and can be merged to

**Comment by isc-tleavitt** [comment]
@daimor I prefer the approach in https://github.com/intersystems/ipm/pull/365/commits/e5856a3eeb5fa63b602312c101bb208268609297 over $System.Version based checking. (I was looking at this yesterday too.)

Going to merge and switch over to that in this PR and see how it works.

**Comment by daimor** [comment]
Yeah, true, this looks better, I'll update

**Comment by isc-tleavitt** [comment]
> Yeah, true, this looks better, I'll update

Even better! I'll hold off and rebase #365 once these fixes are in. Thanks for jumping in on this!

**Comment by isc-tleavitt** [comment]
Also going to push for a new release to fix the 2023.1 installation issue. (Should be an easy case to make. :))

**Comment by isc-tleavitt** [comment]
@daimor I just grabbed this (because I had time), let's see how it runs now.

**Review by isc-tleavitt — APPROVED** [review]

**Comment by isc-tleavitt** [comment]
Woohoo, finally green.

**Pull request merged**
