### PR TITLE
V1next internal xslt

### PR DESCRIPTION
**Pull request by isc-shuliu**
Implement #501

### CODE REVIEW

**Comment by isc-shuliu** [comment]
Here's the current comparison between module.xml and <module-name>.ZPM.

image

**Comment by isc-shuliu** [comment]
@isc-tleavitt Can you confirm this is what we want? Or do we need some more wrapper around `<module>...<module/>` in modulename.ZPM?

**Comment by isc-tleavitt** [comment]
> @isc-tleavitt Can you confirm this is what we want? Or do we need some more wrapper around `<module>...<module/>` in modulename.ZPM?

This looks right to me appearance-wise!!

**Review by isc-tleavitt — APPROVED** [review]
I think this looks good but I'd like @isc-kiyer's eyes on it too.

**Review by isc-kiyer — APPROVED** [review]

**Pull request merged**
