### PR TITLE
v1 - reintroduce support for inc/rtn under PKG resource

### LINKED ISSUE #483: v1 - fix support for rtn/inc within PKG resource
From discussion in #428 - need to enable other document types in https://github.com/intersystems/ipm/blob/v1/src/cls/IPM/Storage/ResourceReference.cls#L129 same as https://github.com/intersystems/ipm/blob/master/src/%25ZPM/PackageManager/Developer/ResourceReference.cls#L125 and account for this so that only documents not explicitly listed in *any* module are exported.

### PR DESCRIPTION
**Pull request by isc-tleavitt**
Fixes #483

### CODE REVIEW

**Comment by isc-tleavitt** [comment]
@isc-kiyer @isc-bzhang I was unable to reproduce the issues related to this that were brought up in past conversation, though I did add unit tests around the case that we were worried about (that passed without needing any related code changes beyond reintroducing the line that was removed).

If you have or can find more information on why the other types were removed, that would be great. Is it possible that the source control extension could be misbehaving here?

**Comment by isc-tleavitt** [comment]
@isc-bzhang (if you have bandwidth) @isc-kiyer (if not) bumping this back up. Would be good to know what the issues really were.

**Comment by isc-tleavitt** [comment]
@isc-kiyer @isc-shuliu bumping this up again - trying to clean up old PRs and would like to get this merged.

**Review by isc-kiyer — APPROVED** [review]
@isc-tleavitt approving with the caveat that we may need some assistance with the source control hooks when adopting to make sure everything still works fine. I do like this change since it means we can reduce the number of .INC resources we have in our module.xml

**Pull request merged**
